version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/db
      NODE_ENV: development
    command: sh -c "
      npx prisma generate &&
      sleep 5 &&
      npx prisma migrate dev --name init &&
      npm run start:dev
      "

  postgres:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
